spring.application.name=eurekaserver
server.port=8761

eureka.instance.hostname=eurekaserver
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.prefer-ip-address=true

eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
